export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SECTION = "FILTER_PRODUCTS_BY_SECTION";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_WISHLIST = "CLEAR_WISHLIST";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const CREATE_ORDERSERVICE = "CREATE_ORDERSERVICE";
export const CLEAR_SERVICEREQUEST = "CLEAR_SERVICEREQUEST";
export const CLEAR_ORDERSERVICE = "CLEAR_ORDERSERVICE";
export const FETCH_ORDERSERVICES = "FETCH_ORDERSERVICES";

